hibernate:
  dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: th05081998


  admin:
    password: admin
    username: admin
#  datasource:
#    data: classpath:/sql/import-h2.sql
#    driver-class-name: org.h2.Driver
#    password: 1
#    platform: h2
#    url: jdbc:h2:mem:blog_simple_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    defer-datasource-initialization: 'true'
    generate-ddl: true
    hibernate:
      ddl-auto: update
  queries:
    roles-query: select u.username, r.role from user u inner join user_role ur on(u.user_id=ur.user_id)
      inner join role r on(ur.role_id=r.role_id) where u.username=?
    users-query: select username, password, active from user where username=?
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  security::
    oauth2:
      client:
        registration:
          google:
            client-id: 382756130761-c77mnm7m4ldon2072i1pbr6vm0eahrm0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1008222593195422
            client-secret: 40d2cc481b88f7e15146a3d11ac4e1f4
            scope:
              - email
              - public_profile
    
# client-id: 382756130761-c77mnm7m4ldon2072i1pbr6vm0eahrm0.apps.googleusercontent.com
#                client-secret: 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
