hibernate:
  dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qlsanbong
    username: root
    password: th05081998

  #  datasource:
  #    data: classpath:/sql/import-h2.sql
  #    driver-class-name: org.h2.Driver
  #    password: 1
  #    platform: h2
  #    url: jdbc:h2:mem:blog_simple_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #    username: sa
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  jpa:
    defer-datasource-initialization: 'true'
    generate-ddl: true
    hibernate:
      ddl-auto: create


